version: '3.9'

services:
  mariadb:
    image: mariadb:latest
    ports:
      - 3306:3306
    environment:
      - MARIADB_USER=manager
      - MARIADB_PASSWORD=pass
      - MARIADB_ROOT_PASSWORD=pass
      - MARIADB_DATABASE=bookstore

  booksapi:
    image: booksapi
    environment:
      - MARIADB_HOST=mariadb
    depends_on:
      - mariadb
    expose:
      - "8000"
    deploy:
      replicas: 2
    
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - booksapi
    ports:
      - "4000:4000"