version: '3.9'

services:
  mariadb:
    image: mariadb:latest
    ports:
      - 3306:3306
    environment:
      - MARIADB_USER=manager
      - MARIADB_PASSWORD=pass
      - MARIADB_ROOT_PASSWORD=pass
      - MARIADB_DATABASE=bookstore

  booksapi:
    build: ./books_api
    environment:
      - MARIADB_HOST=mariadb
    depends_on:
      - mariadb
  
  ordersapi:
    build: ./orders_api
